apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: default
  labels:
    app: cartservice
    version: "v1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
        version: "v1"
    spec:
      containers:
      - name: cartservice
        image: 851725560519.dkr.ecr.us-east-1.amazonaws.com/aymen-cart-service:1
        imagePullPolicy: Always
        ports:
        - containerPort: 7070
          name: http
        env:
        - name: PORT
          value: "7070"
        - name: NODE_ENV
          value: "production"
        - name: REDIS_HOST
          value: "redis-cart"  # ← Assuming you have redis-cart service
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 7070
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 3
        # Optional: Add security context
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: default
spec:
  selector:
    app: cartservice
  ports:
  - port: 7070
    targetPort: 7070
    protocol: TCP
    name: http
  type: ClusterIP