apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: currencyservice
        image: 851725560519.dkr.ecr.us-east-1.amazonaws.com/aymen-currency-service:2
        ports:
        - containerPort: 7000  # ← CHANGED: Microservices usually use 7000 for currency service
          name: http
        env:
        - name: PORT
          value: "7000"  # ← CHANGED: Match containerPort
        readinessProbe:
          httpGet:                    # ← ADDED: Handler type
            path: /health             # ← Health check endpoint
            port: 7000                # ← Match containerPort
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3         # ← RECOMMENDED
          timeoutSeconds: 5           # ← RECOMMENDED
        livenessProbe:
          httpGet:                    # ← ADDED: Handler type
            path: /health             # ← Health check endpoint
            port: 7000                # ← Match containerPort
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3         # ← RECOMMENDED
          timeoutSeconds: 5           # ← RECOMMENDED
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        # Optional: Add container security context
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
  - name: http        # ← CHANGED: If port 7000, it's likely HTTP not gRPC
    port: 7000        # ← CHANGED: Should match containerPort
    targetPort: 7000  # ← CHANGED: Should match containerPort
    protocol: TCP     # ← ADDED: Explicit protocol