apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: payment-service
        image: 851725560519.dkr.ecr.us-east-1.amazonaws.com/aymen-payment-service:latest
        ports:
        - containerPort: 50051  # ← CHANGED: Standard gRPC port for payment service
          name: grpc
        env:
        - name: PORT
          value: "50051"  # ← CHANGED
        readinessProbe:
          grpc:                    # ← CHANGED: gRPC probe for gRPC service
            port: 50051
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3      # ← ADDED
        livenessProbe:
          grpc:                    # ← CHANGED: gRPC probe for gRPC service
            port: 50051
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3      # ← ADDED
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        # Optional: Add security context for container
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
  - name: grpc
    port: 50051       # ← CHANGED: Standard gRPC port
    targetPort: 50051 # ← CHANGED: Match containerPort
    protocol: TCP     # ← ADDED