apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: recommendation-service
        image: 851725560519.dkr.ecr.us-east-1.amazonaws.com/aymen-recommendation-service:${BUILD_NUMBER}
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  type: ClusterIP
  selector:
    app: recommendation-service
  ports:
  - name: grpc
    port: 5000
    targetPort: 8080
