apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: shipping-service
        image: 851725560519.dkr.ecr.us-east-1.amazonaws.com/aymen-shipping-service:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: CARRIER_API_KEY
          valueFrom:
            secretKeyRef:
              name: shipping-secrets
              key: carrier-api-key
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        readinessProbe:
          httpGet:                    # ← HTTP probe for HTTP service
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
        livenessProbe:
          httpGet:                    # ← HTTP probe for HTTP service
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  type: ClusterIP
  selector:
    app: shipping-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP